# Tests in this file are generated by DyadAI

# Smoke test for Add
@named model = Add()
@test model isa ODESystem

# Smoke test for Add3
@named model = Add3()
@test model isa ODESystem

# Smoke test for BooleanPassThrough
@named model = BooleanPassThrough()
@test model isa ODESystem

# Smoke test for DeMultiplex
@named model = DeMultiplex()
@test model isa ODESystem

# Smoke test for DeMultiplex2
@named model = DeMultiplex2()
@test model isa ODESystem

# Smoke test for DeMultiplex3
@named model = DeMultiplex3()
@test model isa ODESystem

# Smoke test for DeMultiplex4
@named model = DeMultiplex4()
@test model isa ODESystem

# Smoke test for DeMultiplex5
@named model = DeMultiplex5()
@test model isa ODESystem

# Smoke test for DeMultiplex6
@named model = DeMultiplex6()
@test model isa ODESystem

# Smoke test for Division
@named model = Division()
@test model isa ODESystem

# Smoke test for Exponentiation
@named model = Exponentiation()
@test model isa ODESystem

# Smoke test for Feedback
@named model = Feedback()
@test model isa ODESystem

# Smoke test for From_deg
@named model = From_deg()
@test model isa ODESystem

# Smoke test for From_degC
@named model = From_degC()
@test model isa ODESystem

# Smoke test for From_degF
@named model = From_degF()
@test model isa ODESystem

# Smoke test for From_degRk
@named model = From_degRk()
@test model isa ODESystem

# Smoke test for Gain
@named model = Gain()
@test model isa ODESystem

# Smoke test for IntegerPassThrough
@named model = IntegerPassThrough()
@test model isa ODESystem

# Smoke test for IntegerToBoolean
@named model = IntegerToBoolean()
@test model isa ODESystem

# Smoke test for IntegerToReal
@named model = IntegerToReal()
@test model isa ODESystem

# Smoke test for InverseBlockConstraints
@named model = InverseBlockConstraints()
@test model isa ODESystem

# Smoke test for LinearDependency
@named model = LinearDependency()
@test model isa ODESystem

# Smoke test for Max
@named model = Max()
@test model isa ODESystem

# Smoke test for Min
@named model = Min()
@test model isa ODESystem

# Smoke test for MinMax
@named model = MinMax()
@test model isa ODESystem

# Smoke test for MultiProduct
@named model = MultiProduct()
@test model isa ODESystem

# Smoke test for MultiSum
@named model = MultiSum()
@test model isa ODESystem

# Smoke test for Multiplex
@named model = Multiplex()
@test model isa ODESystem

# Smoke test for Multiplex3
@named model = Multiplex3()
@test model isa ODESystem

# Smoke test for Multiplex4
@named model = Multiplex4()
@test model isa ODESystem

# Smoke test for Multiplex5
@named model = Multiplex5()
@test model isa ODESystem

# Smoke test for Multiplex6
@named model = Multiplex6()
@test model isa ODESystem

# Smoke test for Not
@named model = Not()
@test model isa ODESystem

# Smoke test for Product
@named model = Product()
@test model isa ODESystem

# Smoke test for RealPassThrough
@named model = RealPassThrough()
@test model isa ODESystem

# Smoke test for RealToBoolean
@named model = RealToBoolean()
@test model isa ODESystem

# Smoke test for Sqrt
@named model = Sqrt()
@test model isa ODESystem

# Smoke test for StandardDeviation
@named model = StandardDeviation()
@test model isa ODESystem

# Smoke test for Sum
@named model = Sum()
@test model isa ODESystem

# Smoke test for To_deg
@named model = To_deg()
@test model isa ODESystem

# Smoke test for To_degC
@named model = To_degC()
@test model isa ODESystem

# Smoke test for To_degF
@named model = To_degF()
@test model isa ODESystem

# Smoke test for To_degRk
@named model = To_degRk()
@test model isa ODESystem
