# Tests in this file are generated by DyadAI

# Smoke test for ConstantMagneticFlux
@named model = ConstantMagneticFlux()
@test model isa ODESystem

# Smoke test for ConstantMagneticPotentialDifference
@named model = ConstantMagneticPotentialDifference()
@test model isa ODESystem

# Smoke test for ConstantPermeance
@named model = ConstantPermeance()
@test model isa ODESystem

# Smoke test for ConstantReluctance
@named model = ConstantReluctance()
@test model isa ODESystem

# Smoke test for Crossing
@named model = Crossing()
@test model isa ODESystem

# Smoke test for EighthOfSphere
@named model = EighthOfSphere()
@test model isa ODESystem

# Smoke test for Ground
@named model = Ground()
@test model isa ODESystem

# Smoke test for HalfCylinder
@named model = HalfCylinder()
@test model isa ODESystem

# Smoke test for Idle
@named model = Idle()
@test model isa ODESystem

# Smoke test for LeakageWithCoefficient
@named model = LeakageWithCoefficient()
@test model isa ODESystem

# Smoke test for MagneticFluxSensor
@named model = MagneticFluxSensor()
@test model isa ODESystem

# Smoke test for MagneticPort
@named model = MagneticPort()
@test model isa ODESystem

# Smoke test for MagneticPotentialDifferenceSensor
@named model = MagneticPotentialDifferenceSensor()
@test model isa ODESystem

# Smoke test for QuarterCylinder
@named model = QuarterCylinder()
@test model isa ODESystem

# Smoke test for QuarterSphere
@named model = QuarterSphere()
@test model isa ODESystem

# Smoke test for Short
@named model = Short()
@test model isa ODESystem

# Smoke test for SignalMagneticFlux
@named model = SignalMagneticFlux()
@test model isa ODESystem

# Smoke test for SignalMagneticPotentialDifference
@named model = SignalMagneticPotentialDifference()
@test model isa ODESystem

# Smoke test for VariablePermeance
@named model = VariablePermeance()
@test model isa ODESystem

# Smoke test for VariableReluctance
@named model = VariableReluctance()
@test model isa ODESystem
