# Tests in this file are generated by DyadAI

# Smoke test for BodyRadiation
@named model = BodyRadiation()
@test model isa ODESystem

# Smoke test for Convection
@named model = Convection()
@test model isa ODESystem

# Smoke test for ConvectiveResistor
@named model = ConvectiveResistor()
@test model isa ODESystem

# Smoke test for FixedHeatFlow
@named model = FixedHeatFlow()
@test model isa ODESystem

# Smoke test for FixedTemperature
@named model = FixedTemperature()
@test model isa ODESystem

# Smoke test for HeatCapacitor
@named model = HeatCapacitor()
@test model isa ODESystem

# Smoke test for HeatFlowSensor
@named model = HeatFlowSensor()
@test model isa ODESystem

# Smoke test for HeatPort
@named model = HeatPort()
@test model isa ODESystem

# Smoke test for PrescribedHeatFlow
@named model = PrescribedHeatFlow()
@test model isa ODESystem

# Smoke test for PrescribedTemperature
@named model = PrescribedTemperature()
@test model isa ODESystem

# Smoke test for RelTemperatureSensor
@named model = RelTemperatureSensor()
@test model isa ODESystem

# Smoke test for TemperatureSensor
@named model = TemperatureSensor()
@test model isa ODESystem

# Smoke test for ThermalConductor
@named model = ThermalConductor()
@test model isa ODESystem

# Smoke test for ThermalResistor
@named model = ThermalResistor()
@test model isa ODESystem

# Smoke test for TwoMasses
@named model = TwoMasses()
@test model isa ODESystem
