# Tests in this file are generated by DyadAI

# Smoke test for AccSensor
@named model = AccSensor()
@test model isa ODESystem

# Smoke test for Accelerate
@named model = Accelerate()
@test model isa ODESystem

# Smoke test for AngleSensor
@named model = AngleSensor()
@test model isa ODESystem

# Smoke test for ConstantTorque
@named model = ConstantTorque()
@test model isa ODESystem

# Smoke test for Disc
@named model = Disc()
@test model isa ODESystem

# Smoke test for Fixed
@named model = Fixed()
@test model isa ODESystem

# Smoke test for Flange
@named model = Flange()
@test model isa ODESystem

# Smoke test for IdealGear
@named model = IdealGear()
@test model isa ODESystem

# Smoke test for IdealPlanetary
@named model = IdealPlanetary()
@test model isa ODESystem

# Smoke test for InternalSupport
@named model = InternalSupport()
@test model isa ODESystem

# Smoke test for Move_phi
@named model = Move_phi()
@test model isa ODESystem

# Smoke test for PowerSensor
@named model = PowerSensor()
@test model isa ODESystem

# Smoke test for RelAccSensor
@named model = RelAccSensor()
@test model isa ODESystem

# Smoke test for RelAngleSensor
@named model = RelAngleSensor()
@test model isa ODESystem

# Smoke test for Set_flange_tau
@named model = Set_flange_tau()
@test model isa ODESystem

# Smoke test for Set_phi_start
@named model = Set_phi_start()
@test model isa ODESystem

# Smoke test for Set_w_start
@named model = Set_w_start()
@test model isa ODESystem

# Smoke test for Spring
@named model = Spring()
@test model isa ODESystem

# Smoke test for Torque
@named model = Torque()
@test model isa ODESystem

# Smoke test for Torque2
@named model = Torque2()
@test model isa ODESystem

# Smoke test for TorqueSensor
@named model = TorqueSensor()
@test model isa ODESystem

# Smoke test for TorqueStep
@named model = TorqueStep()
@test model isa ODESystem

# Smoke test for TorqueToAngleAdaptor
@named model = TorqueToAngleAdaptor()
@test model isa ODESystem
