# Tests in this file are generated by DyadAI

# Smoke test for AccSensor
@named model = AccSensor()
@test model isa ODESystem

# Smoke test for Fixed
@named model = Fixed()
@test model isa ODESystem

# Smoke test for Force2
@named model = Force2()
@test model isa ODESystem

# Smoke test for ForceSensor
@named model = ForceSensor()
@test model isa ODESystem

# Smoke test for InternalSupport
@named model = InternalSupport()
@test model isa ODESystem

# Smoke test for MultiSensor
@named model = MultiSensor()
@test model isa ODESystem

# Smoke test for PositionSensor
@named model = PositionSensor()
@test model isa ODESystem

# Smoke test for PowerSensor
@named model = PowerSensor()
@test model isa ODESystem

# Smoke test for RelAccSensor
@named model = RelAccSensor()
@test model isa ODESystem

# Smoke test for RelPositionSensor
@named model = RelPositionSensor()
@test model isa ODESystem

# Smoke test for RelSpeedSensor
@named model = RelSpeedSensor()
@test model isa ODESystem

# Smoke test for Rod
@named model = Rod()
@test model isa ODESystem

# Smoke test for Set_flange_f
@named model = Set_flange_f()
@test model isa ODESystem

# Smoke test for Set_s_start
@named model = Set_s_start()
@test model isa ODESystem

# Smoke test for Set_v_start
@named model = Set_v_start()
@test model isa ODESystem

# Smoke test for SpeedSensor
@named model = SpeedSensor()
@test model isa ODESystem

# Smoke test for Spring
@test model isa ODESystem
@named model = Spring()
